# Generated by Django 2.2.7 on 2021-02-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishName', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=280)),
                ('cuisine', models.CharField(max_length=48)),
                ('likes', models.IntegerField(blank=True)),
            ],
        ),
    ]
