# Generated by Django 2.2.7 on 2021-02-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
